# 校对任务子组件
from frontend.Proofreading.FilterMenu import FilterMenu
from frontend.Proofreading.PaginationBar import PaginationBar
from frontend.Proofreading.ProofreadingTableWidget import ProofreadingTableWidget
