name: Manual Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Check Version
      id: check_version
      shell: pwsh
      run: |
        $version = Get-Content -Path version.txt
        echo "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

    - name: Create Env
      shell: cmd
      run: |
        .\resource\aria2c.exe https://www.python.org/ftp/python/3.12.8/python-3.12.8-embed-amd64.zip -o python.zip
        powershell -Command "Expand-Archive -Path 'python.zip' -DestinationPath 'env'"
        powershell -Command "Remove-Item -Path 'python.zip' -Recurse -Force -ErrorAction SilentlyContinue"

        .\resource\aria2c.exe https://bootstrap.pypa.io/pip/get-pip.py -o get-pip.py
        .\env\python.exe get-pip.py
        powershell -Command "Remove-Item -Path 'get-pip.py' -Recurse -Force -ErrorAction SilentlyContinue"
        powershell -Command "Copy-Item -Path 'resource\python312._pth' -Destination 'env\python312._pth' -Force"

    - name: Install Requirements
      shell: cmd
      run: |
        .\env\python.exe -m pip install --upgrade pip
        .\env\python.exe -m pip install --upgrade setuptools
        .\env\python.exe -m pip install -r requirements.txt
        .\env\python.exe -m pip cache purge

    - name: Copy Files
      shell: cmd
      run: |
        xcopy "env" ".\dist\LinguaGacha\env" /E /I /Q /H /Y
        xcopy "base" ".\dist\LinguaGacha\base" /E /I /Q /H /Y
        xcopy "frontend" ".\dist\LinguaGacha\frontend" /E /I /Q /H /Y
        xcopy "module" ".\dist\LinguaGacha\module" /E /I /Q /H /Y
        xcopy "resource" ".\dist\LinguaGacha\resource" /E /I /Q /H /Y
        xcopy "widget" ".\dist\LinguaGacha\widget" /E /I /Q /H /Y

        copy "01_启动应用.bat" ".\dist\LinguaGacha\"
        copy "main.py" ".\dist\LinguaGacha\"
        copy "version.txt" ".\dist\LinguaGacha\"

        mkdir .\dist\LinguaGacha\input
        mkdir .\dist\LinguaGacha\output

    - name: Compress Archive NV
      shell: cmd
      run: |
        .\resource\7zr.exe a -y -bt -mx3 -mqs -t7z LinguaGacha_${{ steps.check_version.outputs.version }}.7z .\dist\*

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: MANAUL_BUILD_${{ steps.check_version.outputs.version }}
        release_name: LinguaGacha_${{ steps.check_version.outputs.version }}
        draft: true
        prerelease: false

    - name: Upload Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./LinguaGacha_${{ steps.check_version.outputs.version }}.7z
        asset_name: LinguaGacha_${{ steps.check_version.outputs.version }}.7z
        asset_content_type: application/x-7z-compressed